# .github/workflows/cpp-ci.yml

name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build the application
      run: g++ Beispiel_Struct.cpp -o Structures

    #- name: Build the tests
    #  run: g++ test.cpp -o tests

    - name: Run the application
      run: ./Structures
      
    - name: Run clang-tidy
      run: clang-tidy main.cpp -- -std=c++17
      
    - name: Zip the executable
      run: zip setup.zip Structures
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: setup-zip
        path: ./setup.zip
        
    #- name: Run the tests
    #  run: ./tests && echo "All tests passed!"
        
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: setup-zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1  
      env:
        GITHUB_TOKEN: ${{ secrets.SUPERSECRET }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: "Release v1.0.${{ github.run_number }}"
        draft: false
        prerelease: false        
